version: 1.0.{build}
image: Visual Studio 2022
configuration: Release
platform: Any CPU
before_build:
- ps: dotnet restore
build:
  project: optechx.DownloadFile.sln
  verbosity: minimal
after_build:
- ps: Get-ChildItem -Path . -Recurse
