version: 1.0.{build}
image: Visual Studio 2022
configuration: Release
platform: Any CPU
before_build:
- ps: dotnet restore
build:
  project: optechx.DownloadFile.sln
  verbosity: minimal
after_build:
- ps: >-
    Get-ChildItem -Path . -Recurse
    
    New-Item -Path C:\ -ItemType Directory -Name app -Confirm:$false -Force
    
    Test-Path C:\projects\optechx-downloadfile\optechx.DownloadFile\bin\Release\netcoreapp3.1\
    
    Copy-Item -Path C:\projects\optechx-downloadfile\optechx.DownloadFile\bin\Release\netcoreapp3.1\* -Destination C:\app\ -Recurse -Confirm:$false
test_script:
- ps: >-
    & C:\app\optechx.DownloadFile.exe https://ardownload2.adobe.com/pub/adobe/reader/win/AcrobatDC/2101120039/AcroRdrDC2101120039_MUI.exe $env:TMP\AcroRdrDC2101120039_MUI.exe

    Get-ChildItem -Path $Env:TMP -Filter "*.exe"
